services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: shubhhampers:latest
    container_name: shubhhampers
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    ports:
      - "3000:3000"
    restart: unless-stopped

    # ----- Resource limits -----
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g
        reservations:
          cpus: "0.5"
          memory: 512m
    # ---------------------------

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
